from django.urls import path
from .views import (
    RepoCreateView,
    RepoOrganizationCreateView,
    RepoListView,
    RepoDetailView,
    RepoUpdateView,
    RepoDeleteView,
    RepoAdminListView,
    RepoAdminDetailView,
    RepoAdminUpdateView,
    RepoAdminDeleteView,
    RepoAdminCreateView,
    RepoStarView,
    RepoUnstarView,
    RepoStargazersListView,
    UserStarredReposListView,
    RepoForkView,
    RepoForksListView,
    BranchListCreateView,
    BranchDetailView,
    BranchSetDefaultView,
    RepoCommitListCreateView,
    BranchCommitListView,
    CommitDetailView,
    IssueListCreateView,
    IssueDetailView,
    IssueCloseView,
    IssueReopenView,
    IssueCommentListCreateView,
    IssueCommentDetailView,
    PullRequestListCreateView,
    PullRequestDetailView,
    PullRequestCloseView,
    PullRequestReopenView,
    PullRequestCommentListCreateView,
    PullRequestCommentDetailView,
)

urlpatterns = [
    path('', RepoListView.as_view(), name='repo_list'),
    path('create/', RepoCreateView.as_view(), name='repo_create'),
    path('organizations/<int:organization_id>/create/', RepoOrganizationCreateView.as_view(), name='repo_organization_create'),
    path('starred/', UserStarredReposListView.as_view(), name='repo_starred_list'),

    path('<int:pk>/', RepoDetailView.as_view(), name='repo_detail'),
    path('<int:pk>/update/', RepoUpdateView.as_view(), name='repo_update'),
    path('<int:pk>/delete/', RepoDeleteView.as_view(), name='repo_delete'),

    path('<int:pk>/star/', RepoStarView.as_view(), name='repo_star'),
    path('<int:pk>/unstar/', RepoUnstarView.as_view(), name='repo_unstar'),
    path('<int:pk>/stargazers/', RepoStargazersListView.as_view(), name='repo_stargazers'),

    path('<int:pk>/fork/', RepoForkView.as_view(), name='repo_fork'),
    path('<int:pk>/forks/', RepoForksListView.as_view(), name='repo_forks'),

    path('<int:pk>/branches/', BranchListCreateView.as_view(), name='repo_branch_list_create'),
    path('<int:pk>/branches/<int:branch_pk>/', BranchDetailView.as_view(), name='repo_branch_detail'),
    path('<int:pk>/branches/<int:branch_pk>/set-default/', BranchSetDefaultView.as_view(), name='repo_branch_set_default'),
    path('<int:pk>/branches/<int:branch_pk>/commits/', BranchCommitListView.as_view(), name='repo_branch_commits'),

    path('<int:pk>/commits/', RepoCommitListCreateView.as_view(), name='repo_commit_list_create'),
    path('<int:pk>/commits/<int:commit_pk>/', CommitDetailView.as_view(), name='repo_commit_detail'),

    path('<int:pk>/issues/', IssueListCreateView.as_view(), name='repo_issue_list_create'),
    path('<int:pk>/issues/<int:issue_pk>/', IssueDetailView.as_view(), name='repo_issue_detail'),
    path('<int:pk>/issues/<int:issue_pk>/close/', IssueCloseView.as_view(), name='repo_issue_close'),
    path('<int:pk>/issues/<int:issue_pk>/reopen/', IssueReopenView.as_view(), name='repo_issue_reopen'),
    path('<int:pk>/issues/<int:issue_pk>/comments/', IssueCommentListCreateView.as_view(), name='repo_issue_comment_list_create'),
    path('<int:pk>/issues/<int:issue_pk>/comments/<int:comment_pk>/', IssueCommentDetailView.as_view(), name='repo_issue_comment_detail'),

    path('<int:pk>/pulls/', PullRequestListCreateView.as_view(), name='repo_pull_request_list_create'),
    path('<int:pk>/pulls/<int:pr_pk>/', PullRequestDetailView.as_view(), name='repo_pull_request_detail'),
    path('<int:pk>/pulls/<int:pr_pk>/close/', PullRequestCloseView.as_view(), name='repo_pull_request_close'),
    path('<int:pk>/pulls/<int:pr_pk>/reopen/', PullRequestReopenView.as_view(), name='repo_pull_request_reopen'),
    path('<int:pk>/pulls/<int:pr_pk>/comments/', PullRequestCommentListCreateView.as_view(), name='repo_pull_request_comment_list_create'),
    path('<int:pk>/pulls/<int:pr_pk>/comments/<int:comment_pk>/', PullRequestCommentDetailView.as_view(), name='repo_pull_request_comment_detail'),

    path('admin/', RepoAdminListView.as_view(), name='repo_admin_list'),
    path('admin/<int:pk>/', RepoAdminDetailView.as_view(), name='repo_admin_detail'),
    path('admin/<int:pk>/update/', RepoAdminUpdateView.as_view(), name='repo_admin_update'),
    path('admin/<int:pk>/delete/', RepoAdminDeleteView.as_view(), name='repo_admin_delete'),
    path('admin/create/', RepoAdminCreateView.as_view(), name='repo_admin_create'),
]
