# Generated by Django 5.2.16 on 2026-08-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='organizations.organization'),
        ),
    ]
