# Generated by Django 5.2.16 on 2026-08-11 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('repo', '0002_repo_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner__isnull', False)), models.Q(('organization__isnull', False), ('owner__isnull', True)), _connector='OR'), name='repo_has_one_owner'),
        ),
    ]
