# Generated by Django 5.2.16 on 2026-08-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_branch_commit_issue_issuecomment_pullrequest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['-created_at']},
        ),
    ]
